import type { CaptionStyle, Preset } from "./types";

const base: CaptionStyle = {
  font: "black",
  size: 6.5,
  color: "#FFFFFF",
  // Emphasis must not share a colour with the active word, or the AI's picks
  // are invisible — every word turns that colour as it's spoken anyway.
  emphasisColor: "#FF4D6D",
  activeColor: "#FFE600",
  outlineColor: "#000000",
  outline: 0.55,
  shadow: 0.3,
  position: "bottom",
  margin: 18,
  anchor: null,
  uppercase: true,
  mode: "phrase",
  animation: "pop",
  maxWords: 4,
  highlightBox: false,
  boxColor: "#FFE600",
};

export const PRESETS: Preset[] = [
  {
    id: "punch",
    name: "Punch",
    blurb:
      "Uppercase, pops per word. Yellow marks the beat, pink marks the AI's picks.",
    style: { ...base },
  },
  {
    id: "spotlight",
    name: "Spotlight",
    blurb: "One word at a time, filled highlight box on the active word.",
    style: {
      ...base,
      mode: "word",
      size: 8,
      maxWords: 1,
      highlightBox: true,
      color: "#FFFFFF",
      activeColor: "#0B0B0F",
      emphasisColor: "#FF5C4D",
      boxColor: "#FFE600",
      position: "middle",
      margin: 0,
    },
  },
  {
    id: "clean",
    name: "Clean",
    blurb: "Sentence case, tight grotesk, soft outline. Understated.",
    style: {
      ...base,
      font: "grotesk",
      uppercase: false,
      size: 5,
      color: "#FFFFFF",
      emphasisColor: "#7DF9C3",
      activeColor: "#FFFFFF",
      outline: 0.35,
      animation: "none",
      maxWords: 6,
      margin: 14,
    },
  },
  {
    id: "neon",
    name: "Neon",
    blurb: "Violet glow, heavy outline, centre-frame. Reads on any footage.",
    style: {
      ...base,
      font: "impact",
      size: 7.5,
      color: "#F2E9FF",
      emphasisColor: "#FFE600",
      activeColor: "#B388FF",
      outlineColor: "#2A0B4A",
      outline: 0.75,
      shadow: 0.5,
      position: "middle",
      margin: 0,
      maxWords: 3,
    },
  },
  {
    id: "karaoke",
    name: "Karaoke",
    blurb: "Full phrase up front, each word lights up as it's spoken.",
    style: {
      ...base,
      font: "rounded",
      animation: "karaoke",
      uppercase: false,
      size: 5.4,
      color: "#9AA0B4",
      activeColor: "#FFFFFF",
      emphasisColor: "#FF7A59",
      maxWords: 7,
      margin: 16,
    },
  },
  {
    id: "editorial",
    name: "Editorial",
    blurb: "Serif, lower third, no shouting. For talking-head explainers.",
    style: {
      ...base,
      font: "serif",
      uppercase: false,
      size: 4.4,
      color: "#FFFFFF",
      emphasisColor: "#FFD37A",
      activeColor: "#FFFFFF",
      outline: 0.3,
      animation: "none",
      maxWords: 8,
      margin: 12,
    },
  },
];

export const DEFAULT_PRESET = PRESETS[0];
